name: Release

on:
  push:
    branches: [main]
    paths:
      - 'items/**'
      - 'lang/**'
      - 'parser/**'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          python-version: '3.14'

      - run: uv sync

      - run: uv run main.py

      - name: Archive output
        shell: bash
        run: |
          (
            cd output
            zip -r ../output.zip .
          )

      - name: Compose release body
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo '## Changelog' > body.md
          gh api /repos/${{ github.repository }}/releases/generate-notes \
            -f tag_name='${{ github.sha }}' \
            --jq '.body' >> body.md

      - uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.sha }}
          name: ${{ github.sha }}
          body_path: body.md
          files: ./output.zip